output <- c('<html>', '<!-- WebGL Export for 3D Slicer4 powered by XTK -- http://goXTK.com -->', 
'  <head>', 
'  <title>WebGL Export</title>',
'  <script type="text/javascript" src="xtk_edge.js"></script>', 
'  <script type="text/javascript">', 
'      var run = function() {',
"            renderer0 = new X.renderer3D();",
"            renderer0.container = 'r0';",
'            renderer0.init();',
'        scene = new X.object();', 
'        node1 = new X.mesh();',
paste0("        node1.file = '", fname1, "';"),
sprintf('        node1.color = [%0.2f, %0.2f, %0.2f];', rgb(col)),
paste0('        node1.opacity = ', opacity, ';'),
paste0('        node1.visible = ', visible, ';'), 
paste0("        node1.caption = '", caption, "';"),
'        scene.children.push(node);',
)
